Added the Trademark Symbol in md files
syncfusion-content/xamarin-docs pull request #1024
Opened 2024-12-20 07:41 UTC by KrithikaGanesan

Added the Trademark Symbol in md files

2024-12-20 07:42 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/console)**

2024-12-20 07:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/console)**

2024-12-20 07:45 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/129/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-20 07:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/console)**

2024-12-20 07:54 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/)<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [11](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/130/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-20 08:00 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/131/console)**

2024-12-20 08:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/131/console)**

2024-12-20 08:03 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/xamarin-docs/131/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-12-20 08:04 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/console)**

2024-12-20 08:11 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/console)**

2024-12-20 08:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/132/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-20 08:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/console)**

2024-12-20 08:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/133/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-20 08:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/console)**

2024-12-20 08:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/134/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-27 04:56 UTC, RajaVigneshB requested changes

2024-12-27 04:56 UTC, RajaVigneshB commented on Xamarin/StepProgressBar/GettingStarted.md
> +After installing [Essential Studio® for Xamarin](https://www.syncfusion.com/downloads/xamarin), you can find all the required assemblies in the installation folders, {Syncfusion Essential Studio&reg;
trademark is missed in the syncfusion.

2024-12-27 05:39 UTC, KrithikaGanesan commented on Xamarin/StepProgressBar/GettingStarted.md
> +After installing [Essential Studio® for Xamarin](https://www.syncfusion.com/downloads/xamarin), you can find all the required assemblies in the installation folders, {Syncfusion Essential Studio&reg;
Added the trademark for syncfusion

2024-12-27 05:40 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/console)**

2024-12-27 05:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/console)**

2024-12-27 05:48 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [trade](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/142/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-27 11:46 UTC, merged