XAMARIN-43418 : UG content for OpenText and CloseText in SfBackdropPage.
syncfusion-content/xamarin-docs pull request #225
Opened 2022-06-08 04:32 UTC by BalachandarSelvam

Hi Team,

To include UG content for OpenText and CloseText in SfBackdropPage.

Regards,
Balachandar.

2022-06-08 04:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/186/console)**

2022-06-08 04:35 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/186/artifact/cireports/)<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/186/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/186/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/186/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/186/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/186/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/186/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/186/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-08 04:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/187/console)**

2022-06-08 04:53 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/187/artifact/cireports/)<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/187/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/187/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/187/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/187/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/187/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/187/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/187/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-10 05:53 UTC, BalachandarSelvam commented
rebuild

2022-06-10 05:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/191/console)**

2022-06-10 05:59 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/191/artifact/cireports/)<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/191/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/191/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/191/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/191/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/191/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/191/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/191/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-10 09:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/192/console)**

2022-06-10 09:39 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/192/artifact/cireports/)<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/192/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/192/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/192/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/192/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/192/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/192/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/192/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-10 10:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/193/console)**

2022-06-10 10:37 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/193/artifact/cireports/)<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/193/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/193/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/193/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/193/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/193/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/193/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/193/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-10 10:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/194/console)**

2022-06-10 10:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/194/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/194/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/194/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/194/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/194/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/194/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/194/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-14 04:28 UTC, vigneshrameshsync requested changes

2022-06-14 04:28 UTC, vigneshrameshsync commented on Xamarin/Backdrop-Page/Header-Configuration.md
> +You can customize the icon text in the navigation header by setting the OpenText and CloseText properties in SfBackdropPage.
Provide APIs as a link

2022-06-14 04:28 UTC, vigneshrameshsync commented on Xamarin/Backdrop-Page/Header-Configuration.md
> +description: This section explains how to configure a header on the backdrop page by setting icons and also customizing the text for open and close icons.
Change this by referring the getting started page.

2022-06-14 05:00 UTC, BalachandarSelvam commented on Xamarin/Backdrop-Page/Header-Configuration.md
> +description: This section explains how to configure a header on the backdrop page by setting icons and also customizing the text for open and close icons.
Changed the content as per getting started content.

2022-06-14 05:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/203/console)**

2022-06-14 05:01 UTC, BalachandarSelvam commented on Xamarin/Backdrop-Page/Header-Configuration.md
> +You can customize the icon text in the navigation header by setting the OpenText and CloseText properties in SfBackdropPage.
Provided as APIs.

2022-06-14 05:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/203/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/203/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/203/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/203/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/203/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/203/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/203/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-14 05:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/204/console)**

2022-06-14 05:25 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/204/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/204/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/204/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/204/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/204/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/204/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/204/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-15 03:25 UTC, vigneshrameshsync approved these changes
The content is fine.

2022-06-15 03:25 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [OpenAndCloseText](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/215/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/215/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/215/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/215/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/215/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/215/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/215/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-15 04:01 UTC, merged