XAMARIN-43420 : UG content for OpenIconImageSource and CloseIconImageSource in SfBackdropPage
syncfusion-content/xamarin-docs pull request #226
Opened 2022-06-08 09:03 UTC by Shalini-Ashokan

Hi Team,

To include UG content for OpenIconImageSource and CloseIconImageSource in SfBackdropPage.

Regards,
Shalini.

2022-06-14 04:22 UTC, vigneshrameshsync requested changes

2022-06-14 04:22 UTC, vigneshrameshsync commented on Xamarin/Backdrop-Page/Header-Configuration.md
> +You can customize the default icons in the navigation header by setting the OpenIconImageSource and CloseIconImageSource properties in SfBackdropPage.You may also change the image source formats File
It accepts following inputs
- FileImageSource
- UriImageSource
- FontImageSource
- StreamImageSource

2022-06-14 04:22 UTC, vigneshrameshsync commented on Xamarin/Backdrop-Page/Header-Configuration.md
> + ![Open Custom icons](Header-Configuration-images/CustomIconFile.png)
Don't change the image.

2022-06-14 04:22 UTC, vigneshrameshsync commented on Xamarin/Backdrop-Page/Header-Configuration.md
> +You can customize the default icons in the navigation header by setting the OpenIconImageSource and CloseIconImageSource properties in SfBackdropPage.You may also change the image source formats File
Add note for UriImageSource will not work in iOS platform.

2022-06-14 04:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/201/console)**

2022-06-14 04:39 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/201/artifact/cireports/)<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/201/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/201/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/201/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/201/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/201/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/201/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/201/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-14 04:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/202/console)**

2022-06-14 04:48 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/202/artifact/cireports/)<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/202/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/202/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/202/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/202/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/202/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/202/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/202/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-14 05:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/205/console)**

2022-06-14 05:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/205/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/205/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/205/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/205/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/205/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/205/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/205/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-14 06:41 UTC, Shalini-Ashokan commented on Xamarin/Backdrop-Page/Header-Configuration.md
> +You can customize the default icons in the navigation header by setting the OpenIconImageSource and CloseIconImageSource properties in SfBackdropPage.You may also change the image source formats File
Updated a changes sir

2022-06-14 08:10 UTC, Chrispineagunja commented on Xamarin/Backdrop-Page/Header-Configuration.md
> +You can customize the default icons in the navigation header by setting the [`OpenIconImageSource`]() and [`CloseIconImageSource`]() properties in [`SfBackdropPage`](https://help.syncfusion.com/cr/xa
Customize the default icons in the navigation header by setting the [`OpenIconImageSource`]() and [`CloseIconImageSource`]() properties in the [`SfBackdropPage`](https://help.syncfusion.com/cr/xamarin/Syncfusion.XForms.Backdrop.SfBackdropPage.html). It accepts the following inputs:

2022-06-14 08:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/211/console)**

2022-06-14 08:40 UTC, Shalini-Ashokan commented on Xamarin/Backdrop-Page/Header-Configuration.md
> +You can customize the default icons in the navigation header by setting the [`OpenIconImageSource`]() and [`CloseIconImageSource`]() properties in [`SfBackdropPage`](https://help.syncfusion.com/cr/xa
Modified

2022-06-14 08:41 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/211/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/211/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/211/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/211/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/211/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/211/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/211/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-14 10:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/212/console)**

2022-06-14 10:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/212/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/212/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/212/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/212/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/212/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/212/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/212/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-15 04:01 UTC, vigneshrameshsync approved these changes
The content is fine.

2022-06-15 04:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/217/console)**

2022-06-15 04:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UG_ImageIconSource](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/217/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/217/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/217/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/217/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/217/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/217/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/217/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-15 04:09 UTC, merged