XAMARIN-41237 : Prepare UG content for show leading view and show trailing view support.
syncfusion-content/xamarin-docs pull request #227
Opened 2022-06-08 15:59 UTC by BalachandarSelvam

2022-06-08 16:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/189/console)**

2022-06-10 05:52 UTC, BalachandarSelvam commented
rebuild

2022-06-10 05:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/190/console)**

2022-06-10 05:55 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/190/artifact/cireports/)<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/190/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/190/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/190/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/190/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/190/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/190/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/190/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-10 10:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/195/console)**

2022-06-10 11:00 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/195/artifact/cireports/)<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/195/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/195/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/195/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/195/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/195/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/195/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/195/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-10 11:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/196/console)**

2022-06-10 11:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/196/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/196/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/196/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/196/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/196/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/196/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/196/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-14 04:36 UTC, vigneshrameshsync requested changes

2022-06-14 04:36 UTC, vigneshrameshsync commented on Xamarin/Text-Input-Layout/Custom-Icons.md
> +The ShowLeadingView and ShowTrailingView properties in SfTextInputLayout can be used to control the visibility of the leading and trailing views. Even if the content is already loaded in their respec
The [`ShowLeadingView`]() and [`ShowTrailingView`]() properties in [`SfTextInputLayout`](https://help.syncfusion.com/cr/xamarin/Syncfusion.XForms.TextInputLayout.SfTextInputLayout.html) can be used to control the visibility of the leading and trailing views respectively.

2022-06-14 04:36 UTC, vigneshrameshsync commented on Xamarin/Text-Input-Layout/Custom-Icons.md
> +    LeadingViewPosition="Inside"
Remove unnecessary code lines.

2022-06-14 04:36 UTC, vigneshrameshsync commented on Xamarin/Text-Input-Layout/Custom-Icons.md
> +![Visibility customisation](Custom-Icons-images/textInput_icons_img6.gif)
Provide proper file name.

2022-06-14 06:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/207/console)**

2022-06-14 06:44 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/207/artifact/cireports/)<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/207/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/207/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/207/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/207/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/207/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/207/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/207/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-14 06:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/208/console)**

2022-06-14 06:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/208/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/208/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/208/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/208/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/208/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/208/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/208/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-14 07:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/209/console)**

2022-06-14 07:04 UTC, BalachandarSelvam commented on Xamarin/Text-Input-Layout/Custom-Icons.md
> +The ShowLeadingView and ShowTrailingView properties in SfTextInputLayout can be used to control the visibility of the leading and trailing views. Even if the content is already loaded in their respec
Simplified the content from from text.

2022-06-14 07:04 UTC, BalachandarSelvam commented on Xamarin/Text-Input-Layout/Custom-Icons.md
> +    LeadingViewPosition="Inside"
Removed LeadingViewPosition.

2022-06-14 07:04 UTC, BalachandarSelvam commented on Xamarin/Text-Input-Layout/Custom-Icons.md
> +![Visibility customisation](Custom-Icons-images/textInput_icons_img6.gif)
Provided proper file name.

2022-06-14 07:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/209/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/209/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/209/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/209/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/209/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/209/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/209/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-15 03:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/216/console)**

2022-06-15 03:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ShowLeadingView_and_TrailingView](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/216/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/216/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/216/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/216/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/216/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/216/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/216/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-15 03:59 UTC, vigneshrameshsync approved these changes
The content is fine.

2022-06-15 04:01 UTC, merged