XAMARIN-43421 Prepared UG content for EffectsView Color opacity
syncfusion-content/xamarin-docs pull request #234
Opened 2022-06-14 16:37 UTC by TamilarasanGunasekaran

Hi @vigneshrameshsync,
              I have prepared UG content for EffectsView colour opacity customization properties.

2022-06-14 16:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/213/console)**

2022-06-14 17:14 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/214/artifact/cireports/)<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/214/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/214/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/214/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/214/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/214/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/214/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/214/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-16 06:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/219/console)**

2022-06-16 08:42 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/220/artifact/cireports/)<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/220/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/220/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/220/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/220/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/220/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/220/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/220/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-16 08:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/221/console)**

2022-06-16 10:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/222/console)**

2022-06-16 11:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/222/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/222/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/222/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/222/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/222/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/222/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/222/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-16 18:12 UTC, vigneshrameshsync requested changes

2022-06-16 18:12 UTC, vigneshrameshsync commented on Xamarin/Effects-View/Customization.md
> +The [`SelectionColorOpacity`]() property of [`SfEffectsView`](https://help.syncfusion.com/cr/xamarin/Syncfusion.XForms.EffectsView.SfEffectsView.html) is used to gets or sets a value that determines
Please change the content by referring to the below UG 
https://help.syncfusion.com/winui/radial-gauge/axes#radius-customization

2022-06-16 18:12 UTC, vigneshrameshsync commented on Xamarin/Effects-View/Customization.md
> +![Selection Color Opacity customization](Customization_images/EffectsView_Selection_Effect_Opacity.png)
It is just alt text. So, please avoid unwanted cast changes.

2022-06-16 18:12 UTC, vigneshrameshsync commented on Xamarin/Effects-View/Customization.md
> +    HighlightColorOpacity="0.5">
Whether the images captured with default color with opacity values? or customized at sample level?

2022-06-18 06:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/224/console)**

2022-06-18 06:43 UTC, TamilarasanGunasekaran commented on Xamarin/Effects-View/Customization.md
> +The [`HighlightColorOpacity`]() property of [`SfEffectsView`](https://help.syncfusion.com/cr/xamarin/Syncfusion.XForms.EffectsView.SfEffectsView.html) is used to gets or sets a value that determines
I have made changes in description.

2022-06-18 06:43 UTC, TamilarasanGunasekaran commented on Xamarin/Effects-View/Customization.md
> +The [`RippleColorOpacity`]() property of [`SfEffectsView`](https://help.syncfusion.com/cr/xamarin/Syncfusion.XForms.EffectsView.SfEffectsView.html) is used to gets or sets a value that determines the
I have made changes in description.

2022-06-18 06:43 UTC, TamilarasanGunasekaran commented on Xamarin/Effects-View/Customization.md
> +The [`SelectionColorOpacity`]() property of [`SfEffectsView`](https://help.syncfusion.com/cr/xamarin/Syncfusion.XForms.EffectsView.SfEffectsView.html) is used to gets or sets a value that determines
I have made changes in description.

2022-06-18 06:44 UTC, TamilarasanGunasekaran commented on Xamarin/Effects-View/Customization.md
> +![Selection Color Opacity customization](Customization_images/EffectsView_Selection_Effect_Opacity.png)
I have changed.

2022-06-18 06:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/224/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/224/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/224/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/224/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/224/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/224/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/224/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-18 06:45 UTC, TamilarasanGunasekaran commented on Xamarin/Effects-View/Customization.md
> +    HighlightColorOpacity="0.5">
Its sample level image.

2022-06-20 06:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/225/console)**

2022-06-20 06:29 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: Not Started :x:<br/>Failure Reason: [Source Checkout](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/225/)<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/225/)<br/>**

2022-06-20 06:37 UTC, TamilarasanGunasekaran commented
rebuild

2022-06-20 07:28 UTC, TamilarasanGunasekaran commented
rebuild

2022-06-20 07:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/227/console)**

2022-06-20 07:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/227/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/227/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/227/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/227/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/227/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/227/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/227/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-20 09:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/228/console)**

2022-06-20 09:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EffectsView-color-opacity](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/228/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/228/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/228/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/228/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/228/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/228/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/xamarin-docs/228/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-20 09:50 UTC, vigneshrameshsync approved these changes
The changes are fine.

2022-06-20 14:31 UTC, merged