XAMARIN-44314-Prepared UG content for volume 4 promised feature
syncfusion-content/xamarin-docs pull request #400
Opened 2022-11-30 13:47 UTC by Gayathri-github7

Hi Team,

Prepared UG for volume 4 promised feature. Kindly review it and provide your feedback.

With Regards,
Gayathri R

2022-11-30 13:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/389/console)**

2022-11-30 13:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/389/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/389/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/389/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/389/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/389/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/389/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/389/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-05 01:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/390/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/390/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/390/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/390/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/390/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/390/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/390/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-08 05:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/401/console)**

2022-12-08 05:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/401/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/401/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/401/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/401/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/401/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/401/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/401/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-08 13:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/407/console)**

2022-12-08 17:09 UTC, Mohanaraja requested changes
Address the feedback

2022-12-08 17:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/411/console)**

2022-12-08 17:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/411/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/411/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/411/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/411/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/411/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/411/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/411/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-12 09:55 UTC, laksmipriyamurugesan commented on Xamarin/Rich-Text-Editor/Basic-Features.md
> +The Rich Text Editor provides the support to preserve the dictation text after comes with new paragraph and new line using `div` Html tag.
The RichTextEditor supports preserving the dictation text after it comes with a new paragraph and line using the `div` Html tag.

2022-12-12 10:02 UTC, laksmipriyamurugesan commented on Xamarin/Rich-Text-Editor/Basic-Features.md
> +The Rich Text Editor provides the support to restrict the system keyborad visibility while focusing the Rich Text Editor control. The default value is true.
The `RichTextEditor` supports restricting the system keyboard visibility while focusing on the `RichTextEditor` control. The default value is true.

2022-12-13 04:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/414/console)**

2022-12-13 04:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/414/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/414/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/414/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/414/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/414/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/414/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/414/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-13 05:42 UTC, laksmipriyamurugesan commented on Xamarin/Rich-Text-Editor/Basic-Features.md
> +N>It applies to UWP only for users in China and Korea locations. It is not applicable in android an iOS ,Since android and iOS, we can be able to load the WebView resources through an external style
It applies only to UWP users in China and Korean locations. It is not applicable in android and iOS, Since android and iOS can load the WebView resources using an external style sheet.

2022-12-13 06:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/415/console)**

2022-12-13 06:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [UGRTEKeySupport](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/415/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/415/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/415/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/415/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/415/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/415/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/415/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-14 05:43 UTC, Mohanaraja approved these changes
changes are fine

2022-12-14 11:54 UTC, merged