SEO-172844-Xamarin-weblink-validatetor-images
syncfusion-content/xamarin-docs pull request #568
Opened 2023-06-20 13:17 UTC by Edithabich

Hi @MallikaRK ,
Please review the changes have made in image alt text and image names.
Thanks.
Regards,
Edith.

2023-06-20 13:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172844-Xamarin-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/536/console)**

2023-06-20 13:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172844-Xamarin-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/536/)<br/>**

2023-06-21 10:42 UTC, MallikaRK requested changes
Commented

2023-06-21 10:42 UTC, MallikaRK commented on Xamarin/Visual-Studio-Integration/Download-and-Installation.md
> +	![Manage Extension in Xamarin Visual studio](download-and-installation_images/xamarin-manage-extension.PNG)
Check the image folder name again. 
Why you used underscore in image folder name?

2023-06-24 12:09 UTC, Edithabich commented on Xamarin/Visual-Studio-Integration/Download-and-Installation.md
> +	![Manage Extension in Xamarin Visual studio](download-and-installation_images/xamarin-manage-extension.PNG)
resolved

2023-06-24 12:11 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172844-Xamarin-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/542/console)**

2023-06-24 12:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172844-Xamarin-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/542/)<br/>**

2023-06-27 08:52 UTC, MallikaRK approved these changes
Approved

2023-07-19 12:09 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-07-19 12:09 UTC, merged