SEO-174304 - Xamarin page with redirect
syncfusion-content/xamarin-docs pull request #620
Opened 2023-07-26 13:52 UTC by amyprudencekingstone

Hi @MallikaRK ,
Worked on page with redirect in Xamarin docs. Kindly review

2023-07-26 13:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174304-Xamarin-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/573/console)**

2023-07-26 13:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174304-Xamarin-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/573/)<br/>**

2023-07-27 04:41 UTC, MallikaRK requested changes
Commented

2023-07-27 04:41 UTC, MallikaRK commented on Xamarin/ListView/Getting-started.md
>  I> Starting with v16.2.0.x, if you reference Syncfusion assemblies from the trial setup or from the NuGet feed, you also have to include a license key in your projects. Please refer to [Syncfusion li
why you missed the link? are you checked?

2023-08-01 11:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174304-Xamarin-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/577/console)**

2023-08-01 11:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174304-Xamarin-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/577/)<br/>**

2023-09-14 05:25 UTC, SyncfusionBuild commented
Your pull request has been created. Syncfusion support team will validate this commit and publish your changes accordingly.

2023-09-14 05:42 UTC, Choza-rajan approved these changes

2023-09-14 05:48 UTC, anandhan-rajagopal commented on Xamarin/ListView/Getting-started.md
>  I> Starting with v16.2.0.x, if you reference Syncfusion assemblies from the trial setup or from the NuGet feed, you also have to include a license key in your projects. Please refer to [Syncfusion li
Addressed the changes Commit link: https://github.com/syncfusion-content/xamarin-docs/pull/620/commits/703e32cb423a51444c803903be219828abdafcd0

2023-09-20 05:15 UTC, AarthiArjunan commented
Created new PR for these Changes in the latest hotfix branch.
PR Link: https://github.com/syncfusion-content/xamarin-docs/pull/682/files

2023-09-20 05:15 UTC, closed without merging