SEO-174775 Xamarin Redirect Links
syncfusion-content/xamarin-docs pull request #636
Opened 2023-08-09 14:00 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan,

Have changed Xamarin Page with Redirect links.

Regards,
Yvone.

2023-08-09 14:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174775-Xamarin-Redirect-Links-](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/584/console)**

2023-08-09 14:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174775-Xamarin-Redirect-Links-](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/584/)<br/>**

2023-08-14 09:13 UTC, MallikaRK requested changes
Commented

2023-08-14 09:13 UTC, MallikaRK commented on Xamarin/Calendar/Calendar-MVVM.md
> +[How to bind SelectedDates of Calendar in MVVM?](https://support.syncfusion.com/kb/article/8866)
KB link seems in short form. Can you update full URL here?
https://support.syncfusion.com/kb/article/8866/how-to-bind-selecteddates-of-calendar-in-mvvm

2023-08-14 09:21 UTC, Yvone-Atieno commented on Xamarin/Calendar/Calendar-MVVM.md
> +[How to bind SelectedDates of Calendar in MVVM?](https://support.syncfusion.com/kb/article/8866)
updated

2023-08-14 09:24 UTC, Yvone-Atieno commented on Xamarin/DataGrid/Conditional-Styles.md
> +[How to apply the row background color when mouse hover on SfDataGrid in UWP](https://support.syncfusion.com/kb/article/9779)
updated

2023-08-14 09:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174775-Xamarin-Redirect-Links-](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/588/console)**

2023-08-14 09:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174775-Xamarin-Redirect-Links-](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/588/)<br/>**

2023-08-14 13:04 UTC, MallikaRK approved these changes
Approved

2023-08-16 12:37 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-08-16 12:37 UTC, merged