SEO-174775 Page with Redirect Xamarin
syncfusion-content/xamarin-docs pull request #637
Opened 2023-08-09 14:01 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan,

Have changed Xamarin Page with Redirect links.

Regards,
Yvone.

2023-08-09 14:02 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-174775-Page-with-Redirect-Xamarin](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/585/console)**

2023-08-09 14:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174775-Page-with-Redirect-Xamarin](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/585/console)**

2023-08-09 14:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174775-Page-with-Redirect-Xamarin](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/585/)<br/>**

2023-08-14 09:14 UTC, MallikaRK requested changes
Approved

2023-08-16 12:40 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-08-16 12:42 UTC, MallikaRK approved these changes
Approved

2023-08-16 12:54 UTC, merged