Rich Text Editor provides support to IsScrollButtonVisible feature
syncfusion-content/xamarin-docs pull request #645
Opened 2023-08-17 06:55 UTC by HemalathaDuraisamy

Rich Text Editor provides support to IsScrollButtonVisible feature

2023-08-17 06:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [RTEScrollButton](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/589/console)**

2023-08-17 06:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [RTEScrollButton](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/589/)<br/>**

2023-08-22 12:46 UTC, M-A32 requested changes
I have completed the review.

2023-08-22 12:46 UTC, M-A32 commented on Xamarin/Rich-Text-Editor/Customization.md
> +The Rich Text Editor provides support to scroll the benind the Toolbar visible items .The IsScrollButtonVisible Property help to enable and disable the scroll on Toolbar. The default value is false.T
The Rich Text Editor provides support to scroll the benind the Toolbar visible items .The IsScrollButtonVisible Property help to enable and disable the scroll on the Toolbar. The default value is false. The following code example explains how to customize the toolbar appearance.

2023-09-01 04:36 UTC, Mohanaraja requested changes
Address the comments

2023-09-01 04:36 UTC, Mohanaraja commented on Xamarin/Rich-Text-Editor/Customization.md
> +The Rich Text Editor provides support to scroll the benind the Toolbar visible items .The IsScrollButtonVisible Property help to enable and disable the scroll button on the Toolbar. The default value
The Rich Text Editor provides support to scroll behind the Toolbar visible items. The IsScrollButtonVisible Property helps to enable and disable the scroll button on the Toolbar. The default value of IsScrollButtonVisible is false. The following code example explains how to customize the toolbar appearance.

2023-09-12 12:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [RTEScrollButton](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/617/console)**

2023-09-12 12:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [RTEScrollButton](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/617/)<br/>**

2023-09-12 12:18 UTC, Mohanaraja requested changes
Address the comments

2023-09-12 12:18 UTC, Mohanaraja commented on Xamarin/Rich-Text-Editor/Customization.md
> +
Use the below content 

The Rich Text Editor allows scrolling behind the toolbar's visible items. You can enable or disable the scroll button on the toolbar using the IsScrollButtonVisible Property. By default, the value of IsScrollButtonVisible is set to false. The code example below shows how to customize the appearance of the toolbar.

2023-09-12 12:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [RTEScrollButton](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/618/console)**

2023-09-12 12:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [RTEScrollButton](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/618/)<br/>**

2023-09-12 12:23 UTC, HemalathaDuraisamy commented on Xamarin/Rich-Text-Editor/Customization.md
> +
Updated the mentioned corrections

2023-09-12 12:31 UTC, Mohanaraja approved these changes
changes are fine

2023-09-12 12:31 UTC, merged