SEO-175190 Xamarin Redirect
syncfusion-content/xamarin-docs pull request #646
Opened 2023-08-21 07:37 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan,

Have changed Page with Redirect links.

Regards,
Yvone.

2023-08-22 07:45 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175190-Xamarin-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/592/console)**

2023-08-22 07:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175190-Xamarin-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/592/console)**

2023-08-22 07:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175190-Xamarin-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/592/)<br/>**

2023-08-22 08:42 UTC, MallikaRK requested changes
Commented

2023-08-22 08:42 UTC, MallikaRK commented on Xamarin/DataSource/DataSource-GettingStarted.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/account/manage-trials/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essentia
<img width="853" alt="image" src="https://github.com/syncfusion-content/xamarin-docs/assets/44014283/ff79cc4c-ebc3-4cbd-8a4a-535ab1c221db">
revert your changes. check incognito window for this.

2023-08-22 08:42 UTC, MallikaRK commented on Xamarin/DataSource/DataSource-GettingStarted.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/account/manage-trials/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essentia
revert your changes in all places, you made this.

2023-08-22 08:56 UTC, Yvone-Atieno commented on Xamarin/DataSource/DataSource-GettingStarted.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/account/manage-trials/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essentia
reverted changes

2023-08-22 09:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175190-Xamarin-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/595/console)**

2023-08-25 12:47 UTC, MallikaRK approved these changes
Approved

2023-08-29 11:01 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-08-29 11:01 UTC, merged