SEO-175190 Xamarin Page with Redirect
syncfusion-content/xamarin-docs pull request #647
Opened 2023-08-21 07:41 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan,

Have changed Page with Redirect links.

Regards,
Yvone.

2023-08-25 12:52 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175190-Xamarin-Page-with-Redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/598/console)**

2023-08-25 12:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175190-Xamarin-Page-with-Redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/598/console)**

2023-08-25 12:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175190-Xamarin-Page-with-Redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/598/)<br/>**

2023-08-25 13:01 UTC, MallikaRK requested changes
Commented

2023-08-25 13:01 UTC, MallikaRK commented on Xamarin/Backdrop-Page/Getting-Started.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/account/manage-trials/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essentia
revert this changes, Check and correct in all places.

2023-08-25 14:16 UTC, Yvone-Atieno commented on Xamarin/Backdrop-Page/Getting-Started.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/account/manage-trials/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essentia
changes reverted

2023-08-25 14:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175190-Xamarin-Page-with-Redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/599/console)**

2023-08-25 14:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175190-Xamarin-Page-with-Redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/599/)<br/>**

2023-08-26 08:19 UTC, MallikaRK approved these changes
Approved

2023-08-29 11:06 UTC, merged