827622: Publish UG documentation for 2023 Vol 3.
syncfusion-content/xamarin-docs pull request #656
Opened 2023-08-28 14:48 UTC by VikramDevaraj31

827622: Publish UG documentation for 2023 Vol 3.

2023-08-28 14:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/600/console)**

2023-08-28 14:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/600/)<br/>**

2023-09-07 12:01 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/608/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-09-07 12:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/609/console)**

2023-09-07 12:02 UTC, SyncfusionBuild commented
The CI [Job](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/609/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2023-09-07 12:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/609/)<br/>**

2023-09-08 10:42 UTC, ramkumarsync approved these changes

2023-09-08 10:42 UTC, ramkumarsync commented on Xamarin/Pdf-Viewer/Search-For-Text-Instance.md
> +[Xamarin PDF Viewer](https://www.syncfusion.com/xamarin-ui-controls/xamarin-pdf-viewer) provides support to find and highlight texts in the PDF document and you can also perform text search on rotate
[Xamarin PDF Viewer] (https://www.syncfusion.com/xamarin-ui-controls/xamarin-pdf-viewer) provides support to find and highlight texts in normal and rotated PDF documents, and you can also perform text search on rotated texts as well. The following commands are used to perform text search operations:

2023-09-08 10:42 UTC, ramkumarsync commented on Xamarin/Pdf-Viewer/Search-For-Text-Instance.md
> +N>[Xamarin PDF Viewer](https://www.syncfusion.com/xamarin-ui-controls/xamarin-pdf-viewer) does not support diagonal text search.
N>[Xamarin PDF Viewer](https://www.syncfusion.com/xamarin-ui-controls/xamarin-pdf-viewer) does not support diagonal text search for now.

2023-09-08 10:42 UTC, ramkumarsync commented on Xamarin/Pdf-Viewer/Supported-and-Unsupported-features.md
> +** To avoid data loss, the digital signature is rendered in flatten form while loading a document in SfPdfViewer and the flatten can be removed while saving. Support for adding and editing digital si
To avoid data loss, the digital signature will be rendered in flat form (editing can't be done) while loading a document in SfPdfViewer, and it won't be preserved when saving. Support for adding and editing digital signatures is not yet provided.

2023-09-08 11:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/610/console)**

2023-09-08 11:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/610/)<br/>**

2023-09-08 11:51 UTC, florenceliliana requested changes
I have completed the content review.

2023-09-08 11:51 UTC, florenceliliana commented on Xamarin/Pdf-Viewer/overview.md
> +* **Annotations**: Review and annotate a PDF document using the various annotations, such as highlight, underline, strikethrough, squiggly, line, arrow, rectangle, circle, polygon, cloud, polyline in
* **Annotations**: Review and annotate a PDF document using various annotations, such as highlight, underline, strikethrough, squiggly, line, arrow, rectangle, circle, polygon, cloud, polyline ink, ink eraser, custom stamp, sticky note, and free text.

2023-09-08 11:51 UTC, florenceliliana commented on Xamarin/Pdf-Viewer/Supported-and-Unsupported-features.md
> +** To avoid data loss, the digital signature will be rendered in flat form (editing can't be done) while loading a document in SfPdfViewer, and it won't be preserved when saving. Support for adding a
** To avoid data loss, the digital signature will be rendered in flat form (editing can't be done) while loading a document in the SfPdfViewer, and it won't be preserved when saving. Support for adding and editing digital signatures is not yet provided.

2023-09-08 12:15 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/612/console)**

2023-09-08 12:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/612/console)**

2023-09-08 12:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/612/)<br/>**

2023-09-08 12:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/613/console)**

2023-09-08 12:39 UTC, ramkumarsync approved these changes

2023-09-08 12:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [827622_D](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/613/)<br/>**

2023-09-08 12:44 UTC, merged