SEO-174767-Xamarin-Missing-H1
syncfusion-content/xamarin-docs pull request #658
Opened 2023-08-30 13:44 UTC by berylouma

Hello, 

I have worked on the missing H1.

Regards,
Beryl.

2023-09-04 08:52 UTC, Yvone-Atieno requested changes
Commented

2023-09-04 08:52 UTC, Yvone-Atieno commented on Xamarin/Maps/How-To/Load-stream-to-ShapeFileLayer.md
> +# Load map shapefiles as a stream
Include platform name

2023-09-05 08:17 UTC, berylouma commented on Xamarin/Parallax-View/custom-controls.md
> +# Custom controls in Xamarin Parallax View Control
Updated

2023-09-05 08:17 UTC, berylouma commented on Xamarin/Maps/How-To/Load-stream-to-ShapeFileLayer.md
> +# Load map shapefiles as a stream
Updated

2023-09-05 08:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174767-Xamarin-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/602/console)**

2023-09-05 08:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174767-Xamarin-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/602/)<br/>**

2023-09-05 09:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174767-Xamarin-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/603/console)**

2023-09-05 09:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174767-Xamarin-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/603/)<br/>**

2023-09-05 09:05 UTC, Yvone-Atieno approved these changes
Approved

2023-09-20 13:36 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-09-20 13:37 UTC, merged