SEO-175653-Xamarin-Pages-With-Redirects
syncfusion-content/xamarin-docs pull request #664
Opened 2023-09-08 11:33 UTC by berylouma

Hello,

Worked on the links with redirects.

Regards,
Beryl.

2023-09-08 11:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-Xamarin-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/611/console)**

2023-09-08 11:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-Xamarin-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/611/)<br/>**

2023-09-11 13:10 UTC, Yvone-Atieno requested changes
Commented

2023-09-11 13:10 UTC, Yvone-Atieno commented on Xamarin/Busy-Indicator/Getting-Started.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essential Studio Installed loc
revert this change

2023-09-11 13:10 UTC, Yvone-Atieno commented on Xamarin/Calendar/Getting-Started.md
> +I> Starting with v16.2.0.x, if you reference Syncfusion assemblies from the trial setup or from the NuGet feed, you also have to include a license key in your projects. Please refer to [Syncfusion li
Update the correct link

2023-09-12 09:18 UTC, berylouma commented on Xamarin/Busy-Indicator/Getting-Started.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essential Studio Installed loc
Updated the correct link

2023-09-12 09:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-Xamarin-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/616/console)**

2023-09-12 09:33 UTC, berylouma commented on Xamarin/Calendar/Getting-Started.md
> +I> Starting with v16.2.0.x, if you reference Syncfusion assemblies from the trial setup or from the NuGet feed, you also have to include a license key in your projects. Please refer to [Syncfusion li
Updated

2023-09-12 09:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-Xamarin-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/616/)<br/>**

2023-09-12 15:00 UTC, Yvone-Atieno requested changes
Commented

2023-09-13 13:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-Xamarin-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/620/console)**

2023-09-13 13:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-Xamarin-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/620/)<br/>**

2023-09-13 13:05 UTC, berylouma commented on Xamarin/Calendar/Getting-Started.md
> +I> Starting with v16.2.0.x, if you reference Syncfusion assemblies from the trial setup or from the NuGet feed, you also have to include a license key in your projects. Please refer to [Syncfusion li
Updated

2023-09-14 05:25 UTC, Yvone-Atieno approved these changes
Approved

2023-09-29 07:51 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175653-Xamarin-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/656/console)**

2023-09-29 07:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-Xamarin-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/656/console)**

2023-09-29 07:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-Xamarin-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/656/)<br/>**

2023-11-10 09:30 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-11-10 09:30 UTC, merged