SEO-175680-Xamarin-UG-page-with-redirects-link
syncfusion-content/xamarin-docs pull request #673
Opened 2023-09-14 14:08 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-14 14:09 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/625/console)**

2023-09-14 15:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/625/)<br/>**

2023-09-22 09:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/631/console)**

2023-09-22 09:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/631/)<br/>**

2023-09-27 11:24 UTC, Yvone-Atieno requested changes
Commented

2023-09-27 11:24 UTC, Yvone-Atieno commented on Xamarin/Effects-View/Getting-Started.md
> +Syncfusion Xamarin components are available in [nuget.org](https://www.nuget.org). To add SfEffectsView to your project, open the NuGet package manager in Visual Studio, search for [Syncfusion.Xamari
Revert this change

2023-09-28 07:05 UTC, Edithabich commented on Xamarin/Effects-View/Getting-Started.md
> +Syncfusion Xamarin components are available in [nuget.org](https://www.nuget.org). To add SfEffectsView to your project, open the NuGet package manager in Visual Studio, search for [Syncfusion.Xamari
reverted.

2023-09-28 07:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/649/console)**

2023-09-28 07:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/649/)<br/>**

2023-09-28 07:46 UTC, Yvone-Atieno requested changes
Commented

2023-09-28 07:46 UTC, Yvone-Atieno commented on Xamarin/ListView/Grouping.md
> +[Cancel](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.canceleventargs.cancel?f1url=%253FappId%3DDev14IDEF1&l=EN-US&k=k(System.ComponentModel.CancelEventArgs.Cancel)&rd=true&view
Check this link

2023-09-28 07:46 UTC, Yvone-Atieno commented on Xamarin/ListView/Grouping.md
> +[Cancel](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.canceleventargs.cancel?f1url=%253FappId%3DDev14IDEF1&l=EN-US&k=k(System.ComponentModel.CancelEventArgs.Cancel)&rd=true&view
Check this link

2023-09-28 09:52 UTC, Edithabich commented on Xamarin/ListView/Grouping.md
> +[Cancel](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.canceleventargs.cancel?f1url=%253FappId%3DDev14IDEF1&l=EN-US&k=k(System.ComponentModel.CancelEventArgs.Cancel)&rd=true&view
fixed

2023-09-28 09:54 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/652/console)**

2023-09-28 09:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/652/console)**

2023-09-28 10:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-link](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/652/)<br/>**

2023-10-05 08:13 UTC, Yvone-Atieno approved these changes
Approved

2023-10-31 13:17 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-10-31 13:18 UTC, merged