SEO-175680-Xamarin-UG-page-with-redirects-links
syncfusion-content/xamarin-docs pull request #674
Opened 2023-09-14 14:52 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-15 08:37 UTC, Edberg-Vasan commented
rebuild

2023-09-15 08:38 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/626/console)**

2023-09-15 08:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/626/console)**

2023-09-15 08:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/626/)<br/>**

2023-09-21 12:36 UTC, Yvone-Atieno requested changes
Commented

2023-09-21 12:36 UTC, Yvone-Atieno commented on Xamarin/Numeric-Entry/Getting-Started.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/account/manage-trials/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essentia
Revert changes

2023-09-22 09:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/632/console)**

2023-09-22 09:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/632/)<br/>**

2023-09-27 11:30 UTC, Yvone-Atieno requested changes
Commented

2023-09-27 11:30 UTC, Yvone-Atieno commented on Xamarin/Numeric-Entry/Getting-Started.md
> +Syncfusion Xamarin components are available in [nuget.org](https://www.nuget.org). To add SfNumericTextBox to your project, open the NuGet package manager in Visual Studio, search for [Syncfusion.Xam
revert this change

2023-09-27 11:30 UTC, Yvone-Atieno commented on Xamarin/Shimmer/Getting-Started.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/account/manage-trials/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essentia
Revert this change

2023-09-27 11:30 UTC, Yvone-Atieno commented on Xamarin/Shimmer/Getting-Started.md
> +Syncfusion Xamarin components are available in [nuget.org](https://www.nuget.org). To add SfShimmer to your project, open the NuGet package manager in Visual Studio, search for [Syncfusion.Xamarin.Co
Revert this

2023-09-28 07:08 UTC, Edithabich commented on Xamarin/Numeric-Entry/Getting-Started.md
> +Syncfusion Xamarin components are available in [nuget.org](https://www.nuget.org). To add SfNumericTextBox to your project, open the NuGet package manager in Visual Studio, search for [Syncfusion.Xam
resolved

2023-09-28 07:09 UTC, Edithabich commented on Xamarin/Shimmer/Getting-Started.md
> +After installing [Essential Studio for Xamarin](https://www.syncfusion.com/account/manage-trials/downloads), you can find all the required assemblies in the installation folders, {Syncfusion Essentia
resolved

2023-09-28 07:10 UTC, Edithabich commented on Xamarin/Shimmer/Getting-Started.md
> +Syncfusion Xamarin components are available in [nuget.org](https://www.nuget.org). To add SfShimmer to your project, open the NuGet package manager in Visual Studio, search for [Syncfusion.Xamarin.Co
resolved

2023-09-28 07:20 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/650/console)**

2023-09-28 07:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/650/console)**

2023-09-28 07:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/650/)<br/>**

2023-09-28 07:48 UTC, Yvone-Atieno commented on Xamarin/Installation/mac-installer/how-to-download.md
> +1. Syncfusion licensed products will be available in the [License & Downloads](https://www.syncfusion.com/account/login) page under your registered Syncfusion account.
Check this link

2023-09-28 09:56 UTC, Edithabich commented on Xamarin/Installation/mac-installer/how-to-download.md
> +1. Syncfusion licensed products will be available in the [License & Downloads](https://www.syncfusion.com/account/login) page under your registered Syncfusion account.
fixed

2023-09-28 09:57 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/653/console)**

2023-09-28 09:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/653/console)**

2023-09-28 10:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-Xamarin-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/653/)<br/>**

2023-11-01 10:43 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-11-01 10:43 UTC, merged