SEO-176062-xamarin-UG-page-with-redirect
syncfusion-content/xamarin-docs pull request #691
Opened 2023-09-25 06:06 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-25 06:07 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/634/console)**

2023-09-25 06:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/634/console)**

2023-09-25 06:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/634/)<br/>**

2023-09-28 09:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/651/console)**

2023-09-28 09:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/651/)<br/>**

2023-10-05 09:15 UTC, Yvone-Atieno requested changes
Commented

2023-10-05 09:15 UTC, Yvone-Atieno commented on Xamarin/Installation/web-installer/how-to-download.md
> +4. After downloading, the Syncfusion Xamarin trial installer can be unlocked using either the trial unlock key or the Syncfusion registered login credential. More information on generating an unlock
Check all KB links
<img width="670" alt="image" src="https://github.com/syncfusion-content/xamarin-docs/assets/95272306/25025762-4693-4916-a156-e8611cd8eaa5">

2023-10-10 17:04 UTC, Edithabich commented on Xamarin/Installation/web-installer/how-to-download.md
> +4. After downloading, the Syncfusion Xamarin trial installer can be unlocked using either the trial unlock key or the Syncfusion registered login credential. More information on generating an unlock
resolved

2023-10-10 17:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/672/console)**

2023-10-10 17:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/672/)<br/>**

2023-10-17 07:23 UTC, Yvone-Atieno approved these changes
Approved

2023-11-01 12:06 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-11-01 12:06 UTC, merged