SEO-176062-xamarin-UG-page-with-redirects
syncfusion-content/xamarin-docs pull request #692
Opened 2023-09-25 06:27 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-25 06:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/635/console)**

2023-09-25 06:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/635/)<br/>**

2023-10-05 09:17 UTC, Yvone-Atieno requested changes
Commented

2023-10-05 09:17 UTC, Yvone-Atieno commented on Xamarin/Accordion/Accessibility.md
> +[How to get an AccordionItem in Xamarin.Forms (SfAccordion)](https://support.syncfusion.com/kb/article/9978/how-to-get-an-accordionitem-in-xamarin-forms-sfaccordion?isInternalRefresh=False)
Check all KB links

2023-10-10 17:19 UTC, Edithabich commented on Xamarin/Accordion/Accessibility.md
> +[How to get an AccordionItem in Xamarin.Forms (SfAccordion)](https://support.syncfusion.com/kb/article/9978/how-to-get-an-accordionitem-in-xamarin-forms-sfaccordion?isInternalRefresh=False)
resolved

2023-10-10 17:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/673/console)**

2023-10-10 17:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/673/)<br/>**

2023-10-17 07:24 UTC, Yvone-Atieno requested changes
Commented

2023-10-17 07:24 UTC, Yvone-Atieno commented on Xamarin/Accordion/BindableLayout.md
> +[How to work with Accordion with SfListView in Xamarin.Forms (SfAccordion)](https://support.syncfusion.com/kb/article/9966/how-to-work-with-accordion-with-sflistview-in-xamarin-forms-sfaccordion?isIn
Check the above KB links and update properly

2023-10-17 09:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/682/console)**

2023-10-17 09:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-page-with-redirects](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/682/)<br/>**

2023-10-19 09:58 UTC, Yvone-Atieno approved these changes
Approved

2023-11-28 12:23 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-11-28 12:24 UTC, merged