SEO-176062-xamarin-UG-issue
syncfusion-content/xamarin-docs pull request #695
Opened 2023-09-25 12:40 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-25 12:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-issue](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/638/console)**

2023-09-25 12:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-issue](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/638/)<br/>**

2023-10-17 07:51 UTC, Yvone-Atieno requested changes
Commented

2023-10-17 07:51 UTC, Yvone-Atieno commented on Xamarin/Charts/Localization.md
> +[How to localize the labels in Xamarin.Forms Chart](https://support.syncfusion.com/kb/article/8311/how-to-localize-the-labels-in-xamarin-forms-chart?isInternalRefresh=False)
Check this KB link

2023-10-17 07:51 UTC, Yvone-Atieno commented on Xamarin/Charts/appearance.md
> +[How to apply custom fonts in Xamarin.Forms Chart](https://support.syncfusion.com/kb/article/8209/how-to-apply-custom-fonts-in-xamarin-forms-chart?isInternalRefresh=False)
Check all KB links

2023-10-17 09:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-issue](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/683/console)**

2023-10-17 09:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-issue](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/683/)<br/>**

2023-10-17 09:22 UTC, Edithabich commented on Xamarin/Charts/Localization.md
> +[How to localize the labels in Xamarin.Forms Chart](https://support.syncfusion.com/kb/article/8311/how-to-localize-the-labels-in-xamarin-forms-chart?isInternalRefresh=False)
resolved

2023-10-17 09:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-issue](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/684/console)**

2023-10-17 09:23 UTC, Edithabich commented on Xamarin/Charts/appearance.md
> +[How to apply custom fonts in Xamarin.Forms Chart](https://support.syncfusion.com/kb/article/8209/how-to-apply-custom-fonts-in-xamarin-forms-chart?isInternalRefresh=False)
resolved

2023-10-17 09:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-issue](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/684/)<br/>**

2023-10-19 10:00 UTC, Yvone-Atieno approved these changes
Approved

2023-11-28 12:28 UTC, Aishwarya-Ganesan approved these changes
fine,

2023-11-28 12:29 UTC, merged