SEO-176062-xamarin-UG-issues
syncfusion-content/xamarin-docs pull request #696
Opened 2023-09-25 13:05 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-25 13:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-issues](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/639/)<br/>**

2023-10-05 09:38 UTC, Yvone-Atieno requested changes
Commented

2023-10-17 09:28 UTC, Edithabich commented on Xamarin/Charts/export.md
> +[How to apply the PDF document size to Xamarin.Forms Chart](https://support.syncfusion.com/kb/article/7771/how-to-apply-the-pdf-document-size-to-xamarin-forms-chart?isInternalRefresh=False)
resolved

2023-10-17 09:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-issues](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/685/console)**

2023-10-17 09:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-issues](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/685/)<br/>**

2023-10-19 10:01 UTC, Yvone-Atieno approved these changes
Approved

2023-12-07 15:32 UTC, merged