SEO-176062-xamarin-UG-redirect
syncfusion-content/xamarin-docs pull request #698
Opened 2023-09-25 14:33 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-25 14:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/641/console)**

2023-09-25 14:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/641/)<br/>**

2023-10-05 09:40 UTC, Yvone-Atieno requested changes
Commented

2023-10-05 09:40 UTC, Yvone-Atieno commented on Xamarin/CheckBox/Visual-Customization.md
> +[How to get the values of selected checkboxes in a group using Xamarin.Forms](https://support.syncfusion.com/kb/article/9507/how-to-get-the-values-of-selected-checkboxes-in-a-group-using-xamarin-form
Check KB links

2023-10-17 09:36 UTC, Edithabich commented on Xamarin/CheckBox/Visual-Customization.md
> +[How to get the values of selected checkboxes in a group using Xamarin.Forms](https://support.syncfusion.com/kb/article/9507/how-to-get-the-values-of-selected-checkboxes-in-a-group-using-xamarin-form
resolved

2023-10-17 09:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/686/)<br/>**

2023-11-14 13:44 UTC, Yvone-Atieno approved these changes
Approved

2024-01-04 13:54 UTC, merged