SEO-176113-Xamarin-Page-With-Redirect4
syncfusion-content/xamarin-docs pull request #701
Opened 2023-09-26 09:01 UTC by berylouma

Hello, 

I have worked on the links with redirects.

Regards,
Beryl.

2023-09-29 08:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-Xamarin-Page-With-Redirect4](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/659/console)**

2023-09-29 08:41 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Xamarin-Page-With-Redirect4](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/659/)<br/>**

2023-10-03 08:13 UTC, Yvone-Atieno requested changes
Commented

2023-10-03 08:13 UTC, Yvone-Atieno commented on Xamarin/Effects-View/Customization.md
> +[How to get the selected item from ListView while using SfEffectsView within ItemTemplate](https://support.syncfusion.com/kb/article/10193/how-to-get-the-selected-item-from-listview-while-using-effec
Check this link

2023-10-03 08:13 UTC, Yvone-Atieno commented on Xamarin/Radio-Button/Event.md
> +[How to notify the selection changes in Xamarin.Forms radio button (SfRadioButton)](https://support.syncfusion.com/kb/article/9544/how-to-notify-the-selection-changes-in-xamarin-forms-radiobutton-sfr
Check this link

2023-10-05 13:51 UTC, berylouma commented on Xamarin/Radio-Button/Event.md
> +[How to notify the selection changes in Xamarin.Forms radio button (SfRadioButton)](https://support.syncfusion.com/kb/article/9544/how-to-notify-the-selection-changes-in-xamarin-forms-radiobutton-sfr
Done

2023-10-05 13:51 UTC, berylouma commented on Xamarin/Effects-View/Customization.md
> +[How to get the selected item from ListView while using SfEffectsView within ItemTemplate](https://support.syncfusion.com/kb/article/10193/how-to-get-the-selected-item-from-listview-while-using-effec
Done

2023-10-05 13:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-Xamarin-Page-With-Redirect4](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/668/console)**

2023-10-05 13:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Xamarin-Page-With-Redirect4](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/668/)<br/>**

2023-10-09 13:52 UTC, Yvone-Atieno approved these changes
Approved

2023-11-28 13:41 UTC, merged