SEO-176113-Xamarin-Page-With-Redirect
syncfusion-content/xamarin-docs pull request #705
Opened 2023-09-26 09:08 UTC by berylouma

Hello,

I have worked on the links with redirects.

Regards,
Beryl.

2023-09-29 09:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-Xamarin-Page-With-Redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/663/console)**

2023-09-29 09:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Xamarin-Page-With-Redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/663/)<br/>**

2023-10-03 08:08 UTC, Yvone-Atieno requested changes
Commented

2023-10-03 08:08 UTC, Yvone-Atieno commented on Xamarin/Expander/Appearance.md
> +[How to center align the Expander header text in Xamarin.Forms (SfExpander)](https://support.syncfusion.com/kb/article/9908/how-to-center-align-the-expander-header-text-in-xamarin-forms-sfexpander?is
Check this kb link

2023-10-03 08:08 UTC, Yvone-Atieno commented on Xamarin/Installation/install-nuget-packages.md
> +**NuGet** is a Package management system for Visual Studio. It makes it easy to add, update and remove external libraries in our application. Syncfusion publishing all Xamarin  NuGet packages in [nug
Check this link if it's redirecting

2023-10-03 08:08 UTC, Yvone-Atieno commented on Xamarin/Installation/install-nuget-packages.md
> +> From v16.2.0.46 (2018 Volume 2 Service Pack 1) onwards, all the Syncfusion Xamarin components are available as NuGet packages at [nuget.org](https://www.nuget.org/packages?q=Tags:%22xamarin%22+sync
Check this link

2023-10-06 08:31 UTC, berylouma commented on Xamarin/Expander/Appearance.md
> +[How to center align the Expander header text in Xamarin.Forms (SfExpander)](https://support.syncfusion.com/kb/article/9908/how-to-center-align-the-expander-header-text-in-xamarin-forms-sfexpander?is
Corrected

2023-10-06 08:33 UTC, berylouma commented on Xamarin/Installation/install-nuget-packages.md
> +**NuGet** is a Package management system for Visual Studio. It makes it easy to add, update and remove external libraries in our application. Syncfusion publishing all Xamarin  NuGet packages in [nug
Updated the correct link

2023-10-06 08:34 UTC, berylouma commented on Xamarin/Installation/install-nuget-packages.md
> +> From v16.2.0.46 (2018 Volume 2 Service Pack 1) onwards, all the Syncfusion Xamarin components are available as NuGet packages at [nuget.org](https://www.nuget.org/packages?q=Tags:%22xamarin%22+sync
Corrected

2023-10-06 08:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176113-Xamarin-Page-With-Redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/669/console)**

2023-10-06 08:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176113-Xamarin-Page-With-Redirect](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/669/)<br/>**

2023-10-09 13:53 UTC, Yvone-Atieno approved these changes
Approved

2023-11-28 13:50 UTC, merged