SEO-176062_Xamarin UG-page issue links
syncfusion-content/xamarin-docs pull request #706
Opened 2023-09-26 09:23 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-26 09:24 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176062-xamarin-UG-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/643/console)**

2023-09-26 09:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/643/console)**

2023-09-26 09:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/643/)<br/>**

2023-10-05 09:43 UTC, Yvone-Atieno requested changes
Commented

2023-10-05 09:43 UTC, Yvone-Atieno commented on Xamarin/DataForm/Editing.md
> +[How to update editor value based on another editor in Xamarin.Forms DataForm (SfDataForm)](https://support.syncfusion.com/kb/article/9745/how-to-update-editor-value-based-on-another-editor-in-xamari
Check KB links

2023-10-17 11:10 UTC, Edithabich commented on Xamarin/DataForm/Editing.md
> +[How to update editor value based on another editor in Xamarin.Forms DataForm (SfDataForm)](https://support.syncfusion.com/kb/article/9745/how-to-update-editor-value-based-on-another-editor-in-xamari
resolved

2023-10-17 11:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/688/console)**

2023-10-17 11:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/688/)<br/>**

2023-11-10 13:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/700/console)**

2023-11-10 13:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-xamarin-UG-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/700/)<br/>**

2023-11-15 09:28 UTC, Yvone-Atieno approved these changes
Approved

2024-01-04 14:01 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-01-04 14:01 UTC, merged