SEO-176062-xamarin-UG-redirects-links
syncfusion-content/xamarin-docs pull request #709
Opened 2023-09-26 15:21 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-26 15:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/646/console)**

2023-10-05 09:44 UTC, Yvone-Atieno requested changes
Commented

2023-10-05 09:44 UTC, Yvone-Atieno commented on Xamarin/DataGrid/Paging.md
> +[How to have different page size in SfDataPager with SfDataGrid when the device is in horizontal and vertical orientation mode](https://support.syncfusion.com/kb/article/7968/how-to-have-different-pa
Check KB links

2023-10-17 11:28 UTC, Edithabich commented on Xamarin/DataGrid/Paging.md
> +[How to have different page size in SfDataPager with SfDataGrid when the device is in horizontal and vertical orientation mode](https://support.syncfusion.com/kb/article/7968/how-to-have-different-pa
resolved

2023-10-17 11:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-xamarin-UG-redirects-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/689/console)**

2023-11-15 09:31 UTC, Yvone-Atieno approved these changes
Approved

2024-01-04 14:01 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-01-04 14:02 UTC, merged