SEO-176496-xamarin-page-with-redirect-links
syncfusion-content/xamarin-docs pull request #729
Opened 2023-10-15 11:09 UTC by Edithabich

HI @MallikaRK ,
Please review the changes.

Thanks.

Regards,
Edith.

2023-10-15 11:10 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176496-xamarin-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/678/console)**

2023-10-15 11:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176496-xamarin-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/678/console)**

2023-10-15 11:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176496-xamarin-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/678/)<br/>**

2023-10-18 09:52 UTC, Yvone-Atieno requested changes
Commented

2023-10-18 09:52 UTC, Yvone-Atieno commented on Xamarin/Tabbed-View/Getting-Started.md
> +N> To know more about obtaining our components, refer to these links for [Mac](https://help.syncfusion.com/xamarin/installation/mac-installer/how-to-download) and [Windows](https://help.syncfusion.co
Check this link

2023-11-10 15:03 UTC, Edithabich commented on Xamarin/Tabbed-View/Getting-Started.md
> +N> To know more about obtaining our components, refer to these links for [Mac](https://help.syncfusion.com/xamarin/installation/mac-installer/how-to-download) and [Windows](https://help.syncfusion.co
updated

2023-11-10 15:06 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176496-xamarin-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/701/console)**

2023-11-10 15:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176496-xamarin-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/701/console)**

2023-11-10 15:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176496-xamarin-page-with-redirect-links](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/701/)<br/>**

2023-11-23 07:11 UTC, Yvone-Atieno approved these changes
Approved

2024-01-04 14:08 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-01-04 14:08 UTC, merged