RichTextEditor WebView2 feature UG content
syncfusion-content/xamarin-docs pull request #777
Opened 2023-12-11 06:25 UTC by HemalathaDuraisamy

RichTextEditor WebView2 feature UG content

2023-12-11 12:42 UTC, Vikassekar requested changes
as we discuss in the call do the changes under how to topic.

2023-12-12 09:58 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/713/console)**

2023-12-12 10:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/713/console)**

2023-12-12 10:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/713/)<br/>**

2023-12-12 11:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/714/console)**

2023-12-12 11:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/714/)<br/>**

2023-12-12 12:30 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/715/console)**

2023-12-12 12:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/715/console)**

2023-12-12 12:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/715/)<br/>**

2023-12-12 12:36 UTC, Vikassekar requested changes
Please add toc for this file and replace the comments with the feedbacks given.

2023-12-12 12:36 UTC, Vikassekar commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +In some cases the cursor behaviour does not working properly on the RichTextEditor UWP platform. We have implemented the RichTextEditor control using the WebView for rendering the HTML content. Upon
In some cases the cursor does not work properly on the RichTextEditor UWP platform. RichTextEditor control was implemented using the WebView control for rendering the HTML content. The cursor behavior issue was due to this WebView control.

2023-12-12 12:36 UTC, Vikassekar commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +To overcome the issue by using the WebView2 Control on the RichTextEditor UWP platform. We provided the support for change WebView control to WebView2 control at the sample level. At default the cont
In order to overcome this issue, the RichTextEditor UWP platform have provided support to change [WebView](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview) control to [WebView2](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2) control at the sample level. At default the control load with WebView.

2023-12-12 12:36 UTC, Vikassekar commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +N>The WebView2 control does not support the **Any CPU** architecture, but our source project as implemented by Any CPU architecture.So we could not able to implement the WebView2 directly on source.
N>The WebView2 control does not support the **Any CPU** architecture, hence RichTextEditor control provide support to change the renderer element at runtime, Instead of directly implement using WebView2 control. 
N>It applies to UWP only. Since iOS and Android working properly.

2023-12-12 13:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/716/console)**

2023-12-12 13:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/716/)<br/>**

2023-12-12 13:25 UTC, HemalathaDuraisamy commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +In some cases the cursor behaviour does not working properly on the RichTextEditor UWP platform. We have implemented the RichTextEditor control using the WebView for rendering the HTML content. Upon
Updated the mentioned changes

2023-12-12 13:25 UTC, HemalathaDuraisamy commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +To overcome the issue by using the WebView2 Control on the RichTextEditor UWP platform. We provided the support for change WebView control to WebView2 control at the sample level. At default the cont
Updated the mentioned changes

2023-12-12 13:25 UTC, HemalathaDuraisamy commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +N>The WebView2 control does not support the **Any CPU** architecture, but our source project as implemented by Any CPU architecture.So we could not able to implement the WebView2 directly on source.
Updated the mentioned changes

2023-12-12 14:15 UTC, HemalathaDuraisamy commented on Xamarin/Rich-Text-Editor/Basic-Features.md
> +The Rich Text Editor provides support for to implement a common interface that allowing users to switch between the UWP Renderer class WebView and WebView2 at the sample level. At default the control
Updated the mentioned changes

2023-12-13 10:10 UTC, Vikassekar approved these changes

2023-12-13 10:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/719/console)**

2023-12-13 10:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [RTEWebView2](https://jenkins.syncfusion.com/job/Content/job/xamarin-docs/719/)<br/>**

2023-12-13 10:33 UTC, merged

2023-12-18 05:31 UTC, florenceliliana reviewed
The content review is completed.

2023-12-18 05:31 UTC, florenceliliana commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +title: Fix in Xamarin Rich Text Editor control | Syncfusion
title: Fix in Xamarin Rich Text Editor Control | Syncfusion

2023-12-18 05:31 UTC, florenceliliana commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +# Fix cursor behaviour in SfRichTextEditor UWP Platform
# Fix Cursor Behaviour in SfRichTextEditor UWP Platform

2023-12-18 05:31 UTC, florenceliliana commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +In some cases the cursor does not work properly on the RichTextEditor UWP platform. RichTextEditor control was implemented using the WebView control for rendering the HTML content. The cursor behavio
In some cases, the cursor does not work properly on the RichTextEditor UWP platform. RichTextEditor control was implemented using the WebView control for rendering the HTML content. The cursor behavior issue was due to this WebView control.

2023-12-18 05:31 UTC, florenceliliana commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +In order to overcome this issue, the RichTextEditor UWP platform have provided support to change [WebView](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview) control to [WebV
In order to overcome this issue, the RichTextEditor UWP platform has provided support to change the [WebView](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview) control to [WebView2](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2) control at the sample level. At default, the control loads with WebView.

2023-12-18 05:31 UTC, florenceliliana commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +4. Create the Constructor and get the SfRichTextEditor instance as a parameter and it’s used to pass the WebView2 values to the source. Raised the necessary WebView2 events.And the events are
4. Create the Constructor and get the SfRichTextEditor instance as a parameter and it’s used to pass the WebView2 values to the source. Raised the necessary WebView2 events. And the events are:

2023-12-18 05:31 UTC, florenceliliana commented on Xamarin/Rich-Text-Editor/how-to/Fix cursor behaviour in RichTextEditor UWP.md
> +7. Need to get the SfRichTextEditorRenderer instance from the UWP sample MainPage.Xaml.cs. And since a direct reference to it is not available, this is achieved by using FindSfRichTextEditorRenderer(
7. Need to get the SfRichTextEditorRenderer instance from the UWP sample MainPage.Xaml.cs. Since a direct reference to it is not available, this is achieved using the FindSfRichTextEditorRenderer() method.