SEO-180458-Xamarin-ug-redirect-links
syncfusion-content/xamarin-docs pull request #828
Opened 2024-02-26 08:55 UTC by Edithabich

Hi @MallikaRK ,
Kindly review the changes.

Regards,
Edith.

2024-02-26 08:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-180458-Xamarin-ug-redirect-links](https://ci.syncfusion.com/job/Content/job/xamarin-docs/16/console)**

2024-02-26 08:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-180458-Xamarin-ug-redirect-links](https://ci.syncfusion.com/job/Content/job/Xamarin-docs/16/)<br/>**

2024-02-27 11:31 UTC, Yvone-Atieno requested changes
Commented

2024-02-27 11:31 UTC, Yvone-Atieno commented on Xamarin/Maps/MapsProvider.md
> +You can load the custom map providers map such as Google Maps, TomTom using the [`RequestTileUri`](https://help.syncfusion.com/cr/xamarin/Syncfusion.SfMaps.XForms.ImageryLayer.html) event of ImageryL
Update the correct link
![image](https://github.com/syncfusion-content/xamarin-docs/assets/95272306/f0ea0c68-163f-48b6-84dc-41770deeebbf)

2024-02-27 12:31 UTC, Edithabich commented on Xamarin/Maps/MapsProvider.md
> +You can load the custom map providers map such as Google Maps, TomTom using the [`RequestTileUri`](https://help.syncfusion.com/cr/xamarin/Syncfusion.SfMaps.XForms.ImageryLayer.html) event of ImageryL
resolved

2024-02-27 13:07 UTC, Yvone-Atieno approved these changes
Approved

2024-02-28 11:34 UTC, Aishwarya-Ganesan approved these changes

2024-02-28 11:34 UTC, merged