SEO-181194-Xamarin.Forms-Map-Makers-Coverage-Issues
syncfusion-content/xamarin-docs pull request #865
Opened 2024-04-11 15:01 UTC by Faith-Atieno

Hi @gowthamanthavasiyappan,
Pleasse review the changes made
Regards,
Faith

2024-04-11 15:02 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-181194-Xamarin.Forms-Map-Makers-Coverage-Issues](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/console)**

2024-04-11 15:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181194-Xamarin.Forms-Map-Makers-Coverage-Issues](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/console)**

2024-04-11 15:22 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/artifact/cireports/)<br/>Build Location: [SEO-181194-Xamarin.Forms-Map-Makers-Coverage-Issues](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [9](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/25/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-12 09:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-181194-Xamarin.Forms-Map-Makers-Coverage-Issues](https://ci.syncfusion.com/job/Content/job/xamarin-docs/31/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/31/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/31/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/31/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/31/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/31/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/31/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/31/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/31/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-15 04:51 UTC, gowthamanthavasiyappan requested changes
Commented

2024-04-15 04:51 UTC, gowthamanthavasiyappan commented on Xamarin/Maps/Markers.md
> +![Marker icon image in Xamarin.Forms Maps.](\workspace\Content\xamarin-docs\Spell-Checker\Xamarin/Maps/Markers.md)
Revert this type of change for all places and update proper path.

2024-04-18 06:42 UTC, closed without merging

2024-04-18 06:42 UTC, Faith-Atieno commented
rebuild

2024-04-18 06:45 UTC, Faith-Atieno commented on Xamarin/Maps/Markers.md
> +![Marker icon image in Xamarin.Forms Maps.](\workspace\Content\xamarin-docs\Spell-Checker\Xamarin/Maps/Markers.md)
Hi @gowthamanthavasiyappan, kindly am done

2024-04-18 06:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-181194-Xamarin.Forms-Map-Makers-Coverage-Issues](https://ci.syncfusion.com/job/Content/job/xamarin-docs/42/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/42/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/42/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/42/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/42/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/42/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/42/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/42/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/42/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-29 09:45 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-181194-Xamarin.Forms-Map-Makers-Coverage-Issues](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/console)**

2024-04-29 09:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181194-Xamarin.Forms-Map-Makers-Coverage-Issues](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/console)**

2024-04-29 10:02 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/artifact/cireports/)<br/>Build Location: [SEO-181194-Xamarin.Forms-Map-Makers-Coverage-Issues](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [9](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/xamarin-docs/46/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**